name: WTask
api:
- 2.1.0
- 3.0.0
- 3.0.0-ALPHA7
- 3.0.1
- 3.1.0
- 3.0.2
author: 鲸鱼-Whale
main: BlueWhale\WTask\WTask
version: 3.3.2
softdepend: ["EconomyAPI"]

permissions:
  wtask.command.wtask:
    default: op
  wtask.command.wt:
    default: true
  wtask.command.op:
    default: op
  wtask.command.player:
    default: true